name: AWS example workflow
on:
  push:
env:
  BUCKET_NAME: "foodimagekarl"
  AWS_REGION: "us-east-1"
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy index.html to S3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}